spring:
   servlet:
      multipart:
         max-file-size: 20MB
         max-request-size: 20MB
      
   datasource:
      url: jdbc:h2:file:./cards;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      
   jpa:
      show-sql: true
      hibernate: 
         ddl-auto: update
         dialect: org.hibernate.dialect.H2Dialect
