
spring:
   datasource:
      url: jdbc:h2:file:./test3;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      
   jpa:
      show-sql: true
      hibernate: 
         ddl-auto: update
         dialect: org.hibernate.dialect.H2Dialect
