spring:
   servlet:
      multipart:
         max-file-size: 100MB
         max-request-size: 100MB
      
   datasource:
      // url: jdbc:h2:mem:cards
      url: jdbc:mysql://localhost:3306/tablehack
      username: tablehack
      password: tablehack
      driverClassName: com.mysql.cj.jdbc.Driver
      
   jpa:
      show-sql: false
      hibernate: 
         ddl-auto: update
         dialect: org.hibernate.dialect.H2Dialect
